---
title: "Fundamentos de Aquisição da Linguagem"
author: "Ronaldo Lima Jr."
institute: "Universidade de Brasília (UnB)"
format: 
  revealjs: 
    theme: serif
editor: visual
---

# Teorias de Aquisição de segunda língua

# Behaviorismo

## Behaviorismo

A visão behaviorista de aquisição de L2 compartilha dos mesmos princípios de sua visão de aquisição de L1:

-   Aquisição de segunda língua ocorre por meio da criação de hábitos, através da imitação/repetição e de estímulos e reforços
-   *Estímulo-Resposta*: A aprendizagem ocorre por associação de estímulos externos com respostas desejadas
-   *Reforço*: Reforçar respostas corretas aumenta a probabilidade de sua repetição

## Behaviorismo

As críticas também foram as mesmas:

-   *Reducionismo*: A abordagem simplifica a complexidade da aquisição de linguagem
-   *Ignora Processos Mentais*: Não leva em consideração a compreensão interna e processos cognitivos envolvidos na aprendizagem de uma língua

## Aplicação ao ensino de L2 {style="font-size: 90%;"}

O behaviorismo aplicado ao ensino de L2 fez surgir um método de ensino chamada de *Método Audiolingal*, também conhecido como *Army Method*

-   Surgiu nos EUA durante a década de 1950, influenciado por teorias behavioristas e por encomenda das formças armadas durante a Guerra Fria
-   O enfoque era no desenvolvimento das habilidades auditivas e orais
-   Fazia uso intensivo de repetição (*drills*) para reforçar estruturas linguística e para automatizar respostas corretas
-   Estudantes imitavam modelos nativos para desenvolver pronúncia "correta/autêntica", e memorizavam diálogos e frases para promover fluência

## Críticas

-   Foco excessivo em padrões específicos pode limitar a habilidade dos alunos de se adaptarem a diversas situações linguísticas
-   Pouca Ênfase em produção e compreensão escrita
-   Ênfase excessiva em diálogos pré-fabricados, sem espaço para personalização da aprendizagem, uso genuíno da comunicação, e contextualização de acordo com as necessidades dos aprendizes

## Exemplo

::: aside
From <https://youtu.be/Pz0TPDUz3FU?si=m8rTd5SwhOUnZXY6&t=247>
:::

<iframe width="840" height="472" src="https://www.youtube.com/embed/Pz0TPDUz3FU?si=m8rTd5SwhOUnZXY6&amp;start=247" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

</iframe>

# Inatismo

## Inatismo

-   Trata-se da aplicação do Inatismo proposto por Chomsky para aquisição de L1 à aquisição de L2
-   Muitas pesquisas buscaram verificar a existência de uma Gramática Universal (GU) na aquisição de L2
-   Sua aplicação ao ensino de L2 se deu pela proposta do Modelo Monitor, de Stephen Krashen (1978), composto por 5 hipóteses

## Modelo Monitor

1.  Hipótese da **Aquisição x Aprendizagem:**
    -   **Aquisição:** Processo natural e subconsciente de assimilar a linguagem através da exposição (gerando conhecimento implícito)
    -   **Aprendizagem:** Processo consciente de compreender e aplicar regras gramaticais (gerando conhecimento explícito)
    -   A aquisição é a responsável para desenvolver fluência linguística em uma L2
    -   Um falante só consegue acessar o sistema *adquirido* (conhecimento implícito) enquanto utiliza a L2
    -   Um falante só consegue acessar o sistema aprendido (conhecimento explícito) quando tem tempo de parar para *monitorar* a sua língua
    
------------------------------------------------------------------------

2.  Hipótese da **Ordem Natural:**

- Krashen postula que aprendizes de uma L2 passarão pelas mesmas etapas de aprendizagem a despeito de suas L1s.
 

------------------------------------------------------------------------

3.  Hipótese do **Input:**
    -   O input compreensível, ou seja, a exposição à linguagem que é um pouco além do nível atual do aprendiz (i+1), é essencial para a aquisição efetiva
    -   Input significativo é mais valioso do que instrução explícita

------------------------------------------------------------------------

4.  Hipótese do **Filtro Afetivo:**
    -   Fatores afetivos, como motivação, ansiedade e confiança, influenciam a eficácia da aquisição linguística, criando um filtro emocional que bloqueira o *input*, não permitindo que ele se torne *intake*

------------------------------------------------------------------------

5.  Hipótese do **Monitor:**
    -   O "Monitor" refere-se à capacidade de monitorar e corrigir a produção linguística
    -   Ele só pode ser acessado quando se tem tempo para pensar sobre o conheicmento explícito

## Críticas {style="font-size: 80%;"}

-   **Validade Empírica Limitada:** as hipóteses do Modelo Monitor não podem ser testadas de maneira objetiva por meio de experimentos

-   **Sobrevalorização da Aquisição Natural:** a aprendizagem formal pode desempenhar um papel mais significativo em certos contextos ou para certos indivíduos

-   **Falta de Atendimento à Diversidade Individual:** O Modelo não aborda adequadamente as necessidades individuais -- Alguns alunos podem se beneficiar mais de métodos mais formais ou estruturados.

-   **Abordagem Passiva da Aprendizagem:** o Modelo pode levar a uma abordagem passiva da aprendizagem, desconsiderando a importância da participação ativa e do envolvimento do aluno no processo de aprendizagem de línguas

## Krashen ilustrando o Modelo

::: aside
From <https://youtu.be/NiTsduRreug?si=PRAt4UHxli0xb8fu>
:::

<iframe width="840" height="472" src="https://www.youtube.com/embed/NiTsduRreug?si=PRAt4UHxli0xb8fu&amp;start=247" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

# Hipótese do output

Proposta por Merrill Swain, não invalidava o papel do *input*, mas acreditava que *input compreensível* não era suficiente. Principais características:

-   **Papel do Output na Aquisição:** Swain destaca a importância da produção linguística -- *output* -- no processo de aquisição de segunda língua

-   **Consciência na Produção:** a hipótese sugere que a produção ativa de linguagem, especialmente ao tentar expressar conceitos complexos, leva a uma maior *conscientização* linguística

------------------------------------------------------------------------

-   **Geração de Hipóteses:** ao produzir *output*, os aprendizes são desafiados a *formular hipóteses* linguísticas e a *refletir* sobre as estruturas da língua

-   **Feedback Cognitivo:** a produção de output permite que os aprendizes recebam feedback cognitivo sobre suas tentativas, facilitando a internalização de regras gramaticais e vocabulário

-   **Papel da Comunicação:** a hipótese destaca que a produção de output é essencial para a comunicação efetiva, especialmente em situações em que os aprendizes estão envolvidos em interações significativas

## Aplicações Pedagógicas

-   **Ênfase na Produção Ativa:** recomenda a promoção de atividades que incentivem os alunos a produzir linguagem de maneira significativa, em vez de apenas receber input passivo

-   **Atenção à Correção e Feedback:** destaca a importância de fornecer feedback construtivo sobre a produção linguística dos alunos, permitindo que eles corrijam e aprimorem suas habilidades

-   **Abordagem Centrada na Tarefa:** pode apoiar abordagens centradas em tarefas, onde os alunos são desafiados a realizar atividades que envolvem a produção de output para alcançar objetivos específicos

##  {background-color="white" background-image="FundAquis-3_files/output.png" background-size="70%"}

##  {background-color="white" background-image="FundAquis-3_files/input.png" background-size="90%"}

# (Socio)Interacionismo

## Interacionismo

- **Hatch (1978)**: A aquisição não parte da estrutura para o discurso, mas do discurso para a estrutura.
    + Crianças com L1 e aprendizes de L2 têm uma necessidade comunicativa e usam estratégias múltiplas para alncaçar esse objetivo mesmo sem a estrutura impecável

. . .

- **Long (1980)**: importância do *input* + *output* -- analisou intercações entre falantes nativos e não nativos e viu o grande uso de estratégias comunicativas de ambos para se alcançar o objetivo da comunicação

- - -

- Papel do feedback *afetivo* e *cognitivo*
- Papel da correção
- Papel das estratégias comunicativas

## Socio-interacionismo (Teoria Sociocultural)

:::{.callout-note}
## Lantolf & Beckett (2009)
*O funcionamento mental humano resulta da participação em e da apropriação de formas de mediação cultural integradas em atividades sociais*
:::

. . .

:::{.callout-note}
## Lantolf & Thorne (2007)
*Entende-se que os humanos utilizem artefatos culturais já existentes e criem novos que permitam regular suas atividades biológicas e comportamentais*
:::

## Vygotsky

Principais teses

- Não se pode separar o desenvolvimento da linguagem do contexto histórico e social
- Os humanos pensam através da criação e do uso de ferramentas mediadoras
- A linguagem tem papel importante no desenvolvimento mental, sendo ela a principal ferramenta de mediação

. . .

- Mediação (interação, andaimes, ZDP)
- Automediação (fala privada)


## Interação humana na ASL

::: aside
From: <https://youtu.be/G2XBIkHW954?si=UEo4CB9uOxyFOIVf>
:::



<iframe width="840" height="472" src="https://www.youtube.com/embed/G2XBIkHW954?si=UEo4CB9uOxyFOIVf" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</iframe>


# Conexionismo

--- 

:::{.callout-note}
## Conexionismo
A perspectiva conexionista é uma abordagem teórica na aquisição de segunda língua que se baseia nos princípios da *neurociência* e em *modelos computacionais* inspirados no *funcionamento do cérebro*. 
:::

. . .


1. **Redes Neurais Artificiais (RNAs):** A teoria conexionista utiliza modelos computacionais, como redes neurais artificiais, para simular o processo de aprendizagem de uma segunda língua. Essas redes consistem em unidades interconectadas que representam neurônios, e os pesos das conexões entre essas unidades são ajustados durante o processo de aprendizagem.

- - -

2. **Aprendizagem Distribuída:** A perspectiva conexionista destaca a ideia de que o conhecimento linguístico é distribuído de maneira interconectada em toda a rede neural, em oposição à ideia de regras gramaticais isoladas. A aprendizagem ocorre por meio do ajuste contínuo dos pesos das conexões, com a informação sendo armazenada de maneira distribuída.

. . .

3. **Processo Gradual e Incremental:** A aquisição de uma segunda língua é vista como um processo gradual e incremental, no qual os aprendizes acumulam conhecimento ao longo do tempo. A exposição constante à língua-alvo leva a ajustes contínuos nas conexões neurais, resultando em melhorias na proficiência linguística.

- - -

4. **Influência da Experiência:** A teoria conexionista destaca a importância da experiência na aprendizagem de uma segunda língua. A exposição a diferentes contextos linguísticos e a prática constante são fatores cruciais para o desenvolvimento linguístico.

. . .

5. **Generalização e Flexibilidade:** As redes neurais conexionistas são capazes de generalizar padrões aprendidos para novas situações, proporcionando flexibilidade na aplicação do conhecimento linguístico. Isso reflete a capacidade dos aprendizes de adaptar seu conhecimento a uma variedade de contextos linguísticos.

## Redes Neurais Artificiais

::: aside
From: <https://youtu.be/1_c_MA1F-vU?si=jGAiq1ex5vzMBP4o>
:::

<iframe width="840" height="472" src="https://www.youtube.com/embed/1_c_MA1F-vU?si=jGAiq1ex5vzMBP4o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</iframe>

## Aplicações para a sala de aula
- Importância de equilibrar input e output (exposição e produção)
- Testar hipóteses e obter feedback
- Practicar, revisar, avançar a voltar --> ensino cíclico
- Se a aquisição é estocástica, é preciso reforçar na sala de aula os aspectos mais importantes

# Modelo de Aculturação

## Para pensar:
- Por que se diz que língua e cultura são interconectadas? Consegue pensar em exemplos?
- É preciso gostar/admirar a cultura da L2 para poder adquirir a L2? Ajuda? Por quê (não)?

. . . 

- Qual cultura um aprendiz de inglês-L2 deve aprender ao estudar inglês?
- Qual cultura um aprendiz de português-L2 deve aprender ao estudar português?

## Para pensar:

- Consegue pensar em exemplos culturais do Brasil fortemente conectados a língua e que podem ser explorados em sala de aula de português-L2? 

## Modelo de Aculturação

Aprender uma nova língua não é apenas adquirir novas formas linguísticas, mas também envolve a compreensão e incorporação da cultura associada a essa língua. Principais pontos:

. . .

1. **Integração Cultural:** A aculturação destaca a importância de se integrar à cultura da língua-alvo. Isso inclui compreender normas sociais, valores, tradições e comportamentos típicos da comunidade que fala a língua que está sendo aprendida.

- - -

2. **Contextualização Social:** A aprendizagem da língua é vista como parte de um processo social mais amplo. Interagir com falantes nativos e participar de atividades culturais são considerados aspectos essenciais para o desenvolvimento da proficiência na língua.

. . . 

3. **Adaptação Cultural:** Os aprendizes de segunda língua são incentivados a se adaptar culturalmente, o que pode envolver mudanças na maneira de pensar, comportar-se e se comunicar. Isso contribui para uma comunicação mais eficaz e autêntica na nova língua.

- - - 

4. **Consciência Intercultural:** A consciência intercultural é um componente fundamental, pois os aprendizes são encorajados a compreender e apreciar as diferenças culturais entre sua língua nativa e a língua que estão aprendendo. Isso ajuda a evitar mal-entendidos e promove uma comunicação mais eficaz.

. . .

5. **Aprendizagem Integrada:** O modelo da aculturação sugere que a aprendizagem da língua e da cultura devem ser integradas, em vez de separadas. Isso significa que as habilidades linguísticas são desenvolvidas em conjunto com a compreensão cultural para uma experiência de aprendizagem mais completa.

- - -

O Modelo da Aculturação (*Acculturation Model*) de John H. Schumann (1978):

. . .

1. **Fatores Afetivos e Sociais:** Schumann destaca a importância de fatores afetivos e sociais na aquisição de uma segunda língua. Ele sugere que atitudes emocionais e interações sociais influenciam significativamente o processo de aprendizagem.

. . . 

2. **Aculturação:** O termo "aculturação" refere-se à integração do aprendiz na comunidade que fala a segunda língua. Schumann argumenta que quanto mais o aprendiz se acultura à comunidade-alvo, maior será a probabilidade de sucesso na aquisição da língua.

- - -

3. **Variáveis de Aculturação:** Schumann identifica três variáveis principais que afetam a aculturação e, por conseguinte, a aquisição da segunda língua:
   - **Motivação:** A motivação do aprendiz para se integrar à comunidade falante da segunda língua.
   - **Autoconfiança/Ansiedade:** O nível de confiança ou ansiedade experimentado pelo aprendiz ao se comunicar na segunda língua.
   - **Adaptação Social:** A habilidade do aprendiz de se adaptar socialmente à comunidade-alvo.

- - -

4. **Períodos Críticos:** Schumann sugere que existe um "período crítico" durante o qual a aculturação é mais eficaz. Durante esse período, os aprendizes têm uma maior probabilidade de desenvolver proficiência linguística.

. . .

5. **Saída Linguística:** Schumann destaca a importância da "saída linguística", ou seja, a produção ativa da língua-alvo. Ele argumenta que os aprendizes que se envolvem ativamente na comunicação têm maior probabilidade de se aculturar e, portanto, adquirir a língua com sucesso.

## Exemplo de pesquisa

```{=html}
<iframe width="780" height="700" src="https://seer.ufrgs.br/index.php/organon/article/view/122646/85522" title="Webpage example"></iframe>
```

## Críticas

- Não se trata de uma Teoria que abarque a aquisição como um todo, mas de um Modelo que vislumbra acerca de um (importante) aspecto do desenvolvimento de uma nova língua.

# Dinamicismo / Teoria da Complexidade
